#!/usr/bin/env ruby

str = <<-EOF
tge : tiny GE is a tiny queue system like SGE

qsub [shell]        # submit job
qstat               # show queue stats
qdel [pid]          # delete job
qfinish             # use internal
EOF

puts str

